"""add ingestion_jobs

Revision ID: 6edf05ec1a36
Revises: 0013
Create Date: 2026-08-16 19:11:29.077211+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6edf05ec1a36'
down_revision: Union[str, None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_jobs_app_id_running', 'ingestion_jobs', ['app_id'], unique=True, postgresql_where=sa.text("status = 'running'"))
    op.drop_index(op.f('ix_feature_game_features_app_id_cutoff'), table_name='feature_game_features')
    op.drop_index(op.f('ix_feature_market_features_genre_cutoff'), table_name='feature_market_features')
    op.drop_constraint(op.f('feature_review_summary_app_id_key'), 'feature_review_summary', type_='unique')
    op.drop_index(op.f('ix_feature_review_summary_app_id'), table_name='feature_review_summary')
    op.create_index(op.f('ix_feature_review_summary_app_id'), 'feature_review_summary', ['app_id'], unique=True)
    op.create_index(op.f('ix_mart_review_intelligence_app_id'), 'mart_review_intelligence', ['app_id'], unique=False)
    op.drop_index(op.f('ix_model_runs_model_name_stage'), table_name='model_runs')
    op.create_index(op.f('ix_raw_games_app_id'), 'raw_games', ['app_id'], unique=False)
    op.drop_index(op.f('ix_raw_reviews_author'), table_name='raw_reviews')
    op.drop_constraint(op.f('raw_reviews_review_id_key'), 'raw_reviews', type_='unique')
    op.drop_index(op.f('ix_raw_reviews_review_id'), table_name='raw_reviews')
    op.create_index(op.f('ix_raw_reviews_review_id'), 'raw_reviews', ['review_id'], unique=True)
    op.create_index(op.f('ix_raw_reviews_author_steam_id'), 'raw_reviews', ['author_steam_id'], unique=False)
    op.drop_index(op.f('ix_serving_predictions_app_type'), table_name='serving_predictions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_serving_predictions_app_type'), 'serving_predictions', ['app_id', 'prediction_type'], unique=False)
    op.drop_index(op.f('ix_raw_reviews_author_steam_id'), table_name='raw_reviews')
    op.drop_index(op.f('ix_raw_reviews_review_id'), table_name='raw_reviews')
    op.create_index(op.f('ix_raw_reviews_review_id'), 'raw_reviews', ['review_id'], unique=False)
    op.create_unique_constraint(op.f('raw_reviews_review_id_key'), 'raw_reviews', ['review_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_raw_reviews_author'), 'raw_reviews', ['author_steam_id'], unique=False)
    op.drop_index(op.f('ix_raw_games_app_id'), table_name='raw_games')
    op.create_index(op.f('ix_model_runs_model_name_stage'), 'model_runs', ['model_name', 'stage'], unique=False)
    op.drop_index(op.f('ix_mart_review_intelligence_app_id'), table_name='mart_review_intelligence')
    op.drop_index(op.f('ix_feature_review_summary_app_id'), table_name='feature_review_summary')
    op.create_index(op.f('ix_feature_review_summary_app_id'), 'feature_review_summary', ['app_id'], unique=False)
    op.create_unique_constraint(op.f('feature_review_summary_app_id_key'), 'feature_review_summary', ['app_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_feature_market_features_genre_cutoff'), 'feature_market_features', ['genre', 'feature_cutoff_date'], unique=False)
    op.create_index(op.f('ix_feature_game_features_app_id_cutoff'), 'feature_game_features', ['app_id', 'feature_cutoff_date'], unique=False)
    op.drop_index('ix_ingestion_jobs_app_id_running', table_name='ingestion_jobs', postgresql_where=sa.text("status = 'running'"))
    op.drop_table('ingestion_jobs')
    # ### end Alembic commands ###
